{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccm-hivelocity.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ccm-hivelocity.labels" . | nindent 4 }}
stringData:
  {{ .Values.secret.key }}: {{ .Values.env.hivelocityApiKey | b64enc }}
{{- end -}}
